# This file was auto-generated by jrubyfx-generator at 2013-05-10T14:51:06-04:00

require 'jrubyfx'
fxml_root File.dirname(__FILE__)

class MytestingApplication < JRubyFX::Application
  def start(stage)
    with(stage, title: "Mytesting", width: 600, height: 400)
    MytestingController.load_into(stage)
    stage.show()
  end
end

class MytestingController
  include JRubyFX::Controller
  fxml "bindings.fxml"

  # nodes with ruby method-like fx:ids may be accessed directly
  def initialize
    Thread.new do
      t = 0
      loop {
        sleep 0.1
        run_later do
          @test.setValue(Math.sin(t+=0.03))
        end
      }
    end
  end
  def qtestGetType
    java.lang.Double
  end
  def getQtest
    qtestProperty.get
  end
  def setQtest(x)
    qtestProperty.set(x)
  end
  def qtestProperty
    unless @test
      @test = SimpleDoubleProperty.new(self, "qtest")
    end
    @test
  end

end

MytestingApplication.launch
