# This file was auto-generated by jrubyfx-generator at 2013-05-08T14:40:27-04:00

require 'jrubyfx'
fxml_root File.dirname(__FILE__)

class BugApplication < JRubyFX::Application
  def start(stage)
    with(stage, title: "Bug", width: 600, height: 400)
    BugController.load_into(stage)
    stage.show()
  end
end

class BugController
  include JRubyFX::Controller
  fxml "bug.fxml"

  # nodes with ruby method-like fx:ids may be accessed directly
  def initialize
    puts "fx:id=\"tables\" was not injected: check your FXML file 'bug.fxml'." unless @tables
    puts "fx:id=\"schema_details\" was not injected: check your FXML file 'bug.fxml'." unless @schema_details
    puts "fx:id=\"table_data\" was not injected: check your FXML file 'bug.fxml'." unless @table_data
    puts "fx:id=\"x1\" was not injected: check your FXML file 'bug.fxml'." unless @x1
  end

  def table_selected(event)
    # TODO: Auto-generated event handler
    puts "MouseClicked event 'table_selected' called"
  end

end

BugApplication.launch
