# This file was auto-generated by jrubyfx-generator at 2013-05-17T10:50:41-04:00

require 'jrubyfx'
fxml_root File.dirname(__FILE__)

class NoCtrlApplication < JRubyFX::Application
  def start(stage)
    with(stage, title: "Controller") do
      fxml "ctrl.fxml"
      show
    end
  end
end

class FxmlRefController
  include JRubyFX::Controller
  
  def close_it
    puts "Closing it properly"
    Platform.exit
  end
end

NoCtrlApplication.launch
